# -*- coding: utf-8 -*-
"""Untitled33.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qpy7xWlDpPnUSSyNela5hY0aeg8Eyq3N
"""

r = [0.8, 0.95, 0.7, 0.9, 0.85]

n = len(r)
a = []

for i in range(n):
    a.append([r[i], i + 1])

a.sort()

print("Порядок продажи оборудования:")
for x in a:
    print(x[1], end=' ')