# -*- coding: utf-8 -*-
"""Untitled33.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qpy7xWlDpPnUSSyNela5hY0aeg8Eyq3N
"""

S = ["Amazon", "Yahoo", "eBay", "Yahoo", "Yahoo", "Oracle"]
S2 = ["Yahoo", "eBay", "Yahoo", "Oracle"]

n = len(S)
m = len(S2)

i = 0
j = 0

while i < n and j < m:
    if S[i] == S2[j]:
        j += 1
    i += 1

if j == m:
    print("YES")
else:
    print("NO")