# -*- coding: utf-8 -*-
"""Untitled33.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qpy7xWlDpPnUSSyNela5hY0aeg8Eyq3N
"""

# Упражнение 17
# Оптимальный порядок покупки лицензий:
# лицензии с большим коэффициентом роста нужно покупать раньше

r = [1.2, 1.5, 1.1, 1.8, 1.3]

n = len(r)
a = []

for i in range(n):
    a.append([r[i], i + 1])

a.sort(reverse=True)

print("Порядок покупки лицензий:")
for x in a:
    print(x[1], end=' ')

# Упражнение 17(2)
# Оптимальный порядок продажи оборудования:
# оборудование с меньшим коэффициентом убывания нужно продавать раньше

r = [0.8, 0.95, 0.7, 0.9, 0.85]

n = len(r)
a = []

for i in range(n):
    a.append([r[i], i + 1])

a.sort()

print("Порядок продажи оборудования:")
for x in a:
    print(x[1], end=' ')

# Упражнение 18
# Проверка, является ли последовательность S2 подпоследовательностью S

S = ["Amazon", "Yahoo", "eBay", "Yahoo", "Yahoo", "Oracle"]
S2 = ["Yahoo", "eBay", "Yahoo", "Oracle"]

n = len(S)
m = len(S2)

i = 0
j = 0

while i < n and j < m:
    if S[i] == S2[j]:
        j += 1
    i += 1

if j == m:
    print("YES")
else:
    print("NO")